## 00. PyTorch Fundamentals 

Resource notebook: www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
print(torch.__version__)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

1.13.0+cu116


### Introduction to Tensors

In [3]:
### Creating Tensors
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item() # get tensor back as python int

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix 
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0], MATRIX[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with random numbers, look at data, update random numbers. 

In [17]:
# Create Random Tensors with pytorch of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3951, 0.7503, 0.8023, 0.8862],
        [0.0281, 0.4641, 0.2841, 0.1930],
        [0.4030, 0.8035, 0.2565, 0.1767]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (Red, Green, Blue)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [20]:
torch.rand(size=(3, 3))

tensor([[0.4940, 0.9432, 0.6893],
        [0.9259, 0.7622, 0.5365],
        [0.4567, 0.7246, 0.1342]])

In [21]:
### Zeros and ones
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

### Create range of tensors and tensors-like

In [26]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note**: Tensorflow datatypes are one of the three big errors you will run into pytorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # 
                               device="cpu", # what device is your tensor on
                               requires_grad=False) # whether or not to track gradrients
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - do not get datatype from a tensor , can use `tensor.dtype`
2. Tensors not right shape -to get shape from a tensor , can use tensor.shape
3. Tensors not on the right device -to get device from a tensor, can use tensor.device

In [34]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5109, 0.2816, 0.3678, 0.0379],
        [0.3309, 0.7214, 0.3878, 0.9845],
        [0.4323, 0.1262, 0.1597, 0.7197]])

In [35]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device Tensor is ON: {some_tensor.device}")

tensor([[0.5109, 0.2816, 0.3678, 0.0379],
        [0.3309, 0.7214, 0.3878, 0.9845],
        [0.4323, 0.1262, 0.1597, 0.7197]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device Tensor is ON: cpu


### Manipulating Tensors (Tensor operations)
Tensor Operations include :
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication



In [36]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [39]:
# subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [40]:
# Try out pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [41]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix multiplication

too many ways of performing multiplication in neural networks and deep learning

1. Element wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices: www.mathisfun.com/algebra/matrix-multiplying.html

In [42]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: (tensor * tensor)")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: (tensor * tensor)


In [43]:
# MAtrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [44]:
# Matrix multiplication by hand
tensor

tensor([10, 20, 30])

In [45]:
10*7 + 20*2 + 30*3

200

In [46]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.86 ms, sys: 0 ns, total: 1.86 ms
Wall time: 3.21 ms


tensor(1400)

In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 51 µs, sys: 7 µs, total: 58 µs
Wall time: 62 µs


tensor(1400)

In [48]:
tensor = tensor / 10
tensor

tensor([1., 2., 3.])

In [49]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 99 µs, sys: 0 ns, total: 99 µs
Wall time: 102 µs


tensor(14.)

In [50]:
tensor @ tensor

tensor(14.)

### One of the most common errors of deep learning: shape errors

There are two main rules that performing matrix multiplication needs to satisfy:
1. Inner dimensions must match:
* ` (3, 2) @ (3, 2)` wont work
* ` (2, 3) @ (3, 2)` will work

2. The resulting matrix has the shape of the **outer dimensions**
* ` (2,3) @ (3,2) -> (2,2)`
* ` (3,2) @ (2,3) -> (3,3)`

In [51]:
torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape

torch.Size([10, 10])

https://www.matrixmultiplication.xyz

In [52]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7, 10],
                        [8,11],
                        [9,12]])

In [54]:
#torch.mm(tensor_A, tensor_B) # mm alias for matmul

In [55]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues , we can manipulate the shape of one of our tensors using **transpose**


In [56]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [57]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [58]:
tensor_B.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [59]:
# The matrix multiplication operations works when tensor_B is transposeed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}")
output = torch.mm(tensor_A, tensor_B.T)
print(output)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


### finding the min, max, mean, sum etc of tensor values (tensor aggregation)


In [70]:
# Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [71]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [72]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # find the mean

(tensor(46.), tensor(46.))

In [73]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [74]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [75]:
## Finding the positional min , max
x.argmin() # find the index in tensor that has minimum value with argmin

tensor(0)

In [77]:
x.argmax(), x[9] # find the position in tensor that has the maximum value with argmax()

(tensor(9), tensor(91))

In [78]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of input tensor of certain shape but keep the same memory of original tensor
* Stacking - combine multiple tensors on top of each other or side by side (h stack)
* Squeeze - removes all '1' dimensions from a tensor
* Unzqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [86]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [87]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [89]:
# Changing z changes x because the view of a tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [92]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [93]:
# torch.squeeze which removes all single dimensions from target tensor
x_reshaped.shape

torch.Size([1, 9])

In [94]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
x_reshaped.shape

torch.Size([1, 9])

In [96]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Removes extra dimensions from x_reshaped
# print(f"\nNew Tensor: {x_squeezed}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])


In [98]:
# # torch.unaqueeze() - adds a single dimension to a target tensor at a specific dim
# print(f"previous target: {x_squeezed}")
# # x_unsqueezed = x_squeezed
# print(f"previous target: {x_squeezed}")

In [99]:
# torch.permute rearranges the dimensions of the target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))
# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 ->1, 1->2, 2 ->0
x_permuted.shape, x_original.shape # color channels height, width

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

In [100]:
x_original[0, 0, 0]

tensor(0.3581)

## Indexing (selecting data from tensors)
Indexing with pytorch is similar to numpy

In [101]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape((1, 3, 3))
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [102]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [104]:
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [108]:
x[0][1][1]

tensor(5)

In [109]:
x[:, 0]

tensor([[1, 2, 3]])

In [110]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [112]:
x[0, 1, 1]

tensor(5)

In [113]:
x[0, 0, :]

tensor([1, 2, 3])

In [114]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [115]:
x[0][2][2]

tensor(9)

### PyTorch Tensors and Numpy

In [116]:
import torch
import numpy

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [117]:
array.dtype

dtype('float64')

In [118]:
tensor.dtype

torch.float64

In [119]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [120]:
torch.rand(3,3)

tensor([[0.5204, 0.9912, 0.9691],
        [0.1748, 0.3726, 0.7459],
        [0.8103, 0.5532, 0.9328]])

In [121]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

